import type { GetServerSidePropsContext, NextPage } from 'next';
import { getToken, JWT } from 'next-auth/jwt';
import { NextResponse } from 'next/server'


import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.css';

const secret = process.env.NEXTAUTH_SECRET;

const Home: NextPage = ({ token }: JWT) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Auth Example</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>

        <div>
          <img src='/codetier.png' />
        </div>

        <p className={styles.description}>
          Get started{' '}
          <Link href='/api/auth/signin'>
            <a>
              <code className={styles.code}>/api/auth/signin</code>
            </a>
          </Link>
        </p>
      </main>
    </div>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  
  const req = context.req;
  const token = await getToken({ req, secret });

  if (token) {
    return {
      redirect: {
        destination: '/users/profile',
        permanent: false,
      },
    }
  }

  return {
    props: { token }, // will be passed to the page component as props
  };
}

export default Home;
